---
# yamllint disable rule:line-length
# yamllint disable rule:truthy

packages:
  - logrotate

logrotate_conf_file: /etc/logrotate.conf
logrotate_include_dir: /etc/logrotate.d
logrotate_owner: root
logrotate_group: root

logrotate_default_period: weekly
logrotate_default_count: 20
logrotate_default_create:
  mode:
  owner:
  group:

logrotate_default_dateext: true
logrotate_default_compress: true

logrotate_rules:
  - name: syslog
    files:
      - /var/log/cron
      - /var/log/messages
      - /var/log/secure
      - /var/log/spooler
    directives:
      - missingok
      - compress
      - rotate: 90
      - weekly
      - missingok
      - postrotate: |
          /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true

  - name: maillog
    files:
      - /var/log/maillog
    directives:
      - missingok
      - compress
      - rotate: 90
      - weekly
      - missingok
      - postrotate: |
          /usr/bin/systemctl kill -s HUP rsyslog.service >/dev/null 2>&1 || true


...
