---

podman_containers:
  - name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    state: started
    network: host
    pid: host
    command:
      - --path.rootfs=/host
      - --collector.systemd
      - --collector.processes
    volumes:
      - /:/host:ro,rslave
      - /run/systemd/private:/run/systemd/private:ro

...