- name: Initial configuration
  hosts: all
  gather_facts: yes
  strategy: free

  roles:
    - role: roles/role-linux-base
    - role: roles/role-linux-auth
    - role: roles/role-logwatch
    - role: roles/role-logrotate
    - role: roles/role-mail-aliases
