---
# yamllint disable rule:line-length
# yamllint disable rule:truthy

- name: Network configuration
  block:

    - name: Create dummy interface
      community.general.nmcli:
        type: dummy
        ifname: int0
        conn_name: int0
        ip4: "{{ net_dummy_ipv4 }}"
        state: present

  when:
    - net_dummy_ipv4 is defined

  tags:
    - network

...
