---
# yamllint disable rule:line-length
# yamllint disable rule:truthy

- name: Render /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: "/etc/resolv.conf"
    mode: 0644
    backup: yes

...
